### ISSUE TITLE
Perhaps @extends should only copy configured fields?

### ISSUE THREAD

**Issue by beam-sysuser** [perfectsense/gyro#151]
<p>The scenario is this that I created a simple workflow to replace a box. See below. If you trigger this workflow by changing the AMI the <tt>@workflow::create</tt> will fail because the <tt>@extends</tt> will copy the private ip address over which when provided during a create will try to set the private ip to that value. Since it's already used by the existing resource, creation fails:</p>

<p><b>Error:</b></p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Caused by: Unexpected error: software.amazon.awssdk.services.ec2.model.Ec2Exception: Address 172.31.31.193 is in use. (Service: Ec2, Status Code: 400, Request ID: d615405d-a519-4696-ae5d-9d2ee356adbe)</pre>
</div></div>

<p><b>Workflow</b>:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">xenial: <span class="code-quote">"ami-04763b3055de4860b"</span>
bionic: <span class="code-quote">"ami-05ecb1463f8f1ee4b"</span>

aws::instance webserver
    ami: $bionic
    instance-type: <span class="code-quote">"t3.nano"</span>
end

@workflow::define aws::instance replace-instance
    stage <span class="code-keyword">new</span>
@workflow::create aws::instance webserver-<span class="code-keyword">new</span>
    @<span class="code-keyword">extends</span>: $(aws::instance webserver)

    <span class="code-keyword">private</span>-ip-address:
@end

transition swap
    to: swap
    description: <span class="code-quote">'New instance is healthy, swap it in.'</span>
end
    end

    stage swap
@workflow::replace: $(aws::instance webserver) $(aws::instance webserver-<span class="code-keyword">new</span>)
    end
@end</pre>
</div></div>

<i>[GYRO-428] created by beetlebugorg</i>

**Comment by beetlebugorg** [comment]
This is closed since we've implemented `-merge` and `-exclude` parameters to `@extends`. Those can be used to prevent this issue.
