### ISSUE TITLE
$(external-query ..) should support changing the credentials

### ISSUE THREAD

**Issue by beam-sysuser** [perfectsense/gyro#152]
<p>The following example loads the AMI based on the region in the default credentials. Users should be able to pass the credentials and/or they should be able to set the region.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">ami-id: $(external-query aws::ami {
    name: <span class="code-quote">'ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20190628'</span>,
    architecture: <span class="code-quote">'x86_64'</span>,
    root-device-type: <span class="code-quote">'ebs'</span>,
    virtualization-type: <span class="code-quote">'hvm'</span>,
    owner-id: <span class="code-quote">'099720109477'</span>,
    state: <span class="code-quote">'available'</span>
}).0.id</pre>
</div></div>

<i>[GYRO-425] created by beetlebugorg</i>

**Comment by beetlebugorg** [comment]
One last thing. Can you make a PR in `gyro-docs` that updates the `external-query` documentation to include this new option.
