### ISSUE TITLE
Move Copyable<M>.copyFrom(M model) interface method to Resource class

### ISSUE THREAD

**Issue by beam-sysuser** [perfectsense/gyro#157]
The following interface is defined in each provider:

```java
public interface Copyable<M> {
    void copyFrom(M model);
}
```

This method is implemented by all Resources so that they can take part in the `Finder` system (ability to query for resources not managed by Gyro). Currently, each provider implements their own subclass of `Finder` and then uses the `Copyable<M>` interface to instantiate resources returned by the query.

This method should be moved to the `Resource` class to ensure that resources always implement this method. Once this is moved `Finder` can add the following method for providers to use:

```java
    @SuppressWarnings("unchecked")
    protected R newResource(M model) {
        R resource = newResource();
        resource.copyFrom(model);

        return resource;
    }
```

**Comment by beetlebugorg** [comment]
It was decided not to implement this at this time, rather by convention this should be implemented by providers.
