### ISSUE TITLE
Ability to "gyro up <directory>" and have it only see the files in that directory

### ISSUE THREAD

**Issue by beam-sysuser** [perfectsense/gyro#159]
<p>This is a suggestion.</p>

<p>Two primary use cases:</p>

<ul>
	<li><tt>gyro up network/</tt> to build the network environment</li>
	<li><tt>gyro ssh network</tt> to ssh to a box in the network environment (currently can be gateways OR registry boxes)</li>
</ul>

<i>[GYRO-367] created by beetlebugorg</i>

**Comment by beetlebugorg** [comment]
This is how it currently works except in some edge cases where it needs resources outside the given directly.
