### ISSUE TITLE
Allow reference lookups to define multiple names

### ISSUE THREAD

**Issue by beam-sysuser** [perfectsense/gyro#161]
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
security-groups: $(aws::security-group gateway operation)
</pre>
</div></div>

<p>This would return a list of two references.</p>
<i>[GYRO-357] created by beetlebugorg</i>

**Comment by beetlebugorg** [comment]
Couple of notes for this syntax:

- Always return a list
- Support wildcards in names, if a wildcard returns nothing, return an empty list. 
- If a wildcard is combined with a bare name (`a b*`) and the wildcard is empty, return a list with just `a`. If `a` doesn't exists, it's an error.
