### ISSUE TITLE
Exception saving state when implicit reference resource lookup fails

### ISSUE THREAD

**Issue by beam-sysuser** [perfectsense/gyro#166]
<p>Note: This may be related to <tt>@extends</tt> when used in a Workflow since it appears to be doing the right thing outside a workflow.</p>

<p>State fails with a NPE if one of the values of a resource is a reference that was implicitly looked up via it's string value but the actual reference doesn't exist.</p>

<p>STR:</p>

<p>Create a Launch Configuration with a <tt>key</tt> that doesn't exist as a string value. Example below.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">aws::launch-configuration frontend
    name: <span class="code-quote">"frontend"</span>
    ami-id: <span class="code-quote">"ami-04328208f4f0cf1fe"</span>
    instance-type: <span class="code-quote">"t2.micro"</span>
    key: <span class="code-quote">"example"</span>
    security-groups: [
$(aws::security-group frontend)
    ]
end</pre>
</div></div>

<p>Gyro will error with a NPE at: <a href="https://github.com/perfectsense/gyro/blob/692f27f7c2397e7856b5d0f2f0f945bfe2b9b4d3/lang/src/main/java/gyro/lang/ast/value/ValueNode.java#L18" class="external-link" rel="nofollow">https://github.com/perfectsense/gyro/blob/692f27f7c2397e7856b5d0f2f0f945bfe2b9b4d3/lang/src/main/java/gyro/lang/ast/value/ValueNode.java#L18</a></p>

<p>It appears the reason for this is that Gyro is trying to build a reference to the key pair for state (<tt>$(aws::key-pair <name>)</tt>) but since this doesn't exist in the configs it doesn't have a resource name.</p>

<p>You can see how it tries to grab the name here: <a href="https://github.com/perfectsense/gyro/blob/692f27f7c2397e7856b5d0f2f0f945bfe2b9b4d3/core/src/main/java/gyro/core/scope/State.java#L323" class="external-link" rel="nofollow">https://github.com/perfectsense/gyro/blob/692f27f7c2397e7856b5d0f2f0f945bfe2b9b4d3/core/src/main/java/gyro/core/scope/State.java#L323</a></p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Error: Can't replace aws::launch-configuration frontend resource!

Caused by: Unexpected error: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
	at gyro.lang.ast.value.ValueNode.<init>(ValueNode.java:18)
	at gyro.core.scope.State.toNode(State.java:323)
	at gyro.core.scope.State.toPairNode(State.java:278)
	at gyro.core.scope.State.toBodyNodes(State.java:253)
	at gyro.core.scope.State.save(State.java:202)
	at gyro.core.diff.Diff.executeChange(Diff.java:402)
	at gyro.core.diff.Diff.executeCreateKeepUpdate(Diff.java:333)
	at gyro.core.diff.Diff.execute(Diff.java:325)
	at gyro.core.workflow.Stage.execute(Stage.java:102)
	at gyro.core.workflow.Workflow.execute(Workflow.java:88)
	at gyro.core.diff.Replace.execute(Replace.java:107)
	at gyro.core.diff.Diff.executeChange(Diff.java:385)
	at gyro.core.diff.Diff.executeReplace(Diff.java:345)
	at gyro.core.diff.Diff.execute(Diff.java:326)
	at gyro.core.command.UpCommand.doExecute(UpCommand.java:32)
	at gyro.core.command.AbstractConfigCommand.doExecute(AbstractConfigCommand.java:118)
	at gyro.core.command.AbstractCommand.execute(AbstractCommand.java:57)
	at gyro.cli.Gyro.run(Gyro.java:191)
	at gyro.cli.Gyro.main(Gyro.java:75)</pre>
</div></div>

<i>[GYRO-304] created by beetlebugorg</i>

**Comment by beetlebugorg** [comment]
Another example of this is using an external-query within a resource.

```
google::instance gyro-dev-1
    name: "gyro-development"
    description: "Testing for Gyro"
    zone: "us-west1-a"
    machine-type: "https://www.googleapis.com/compute/v1/projects/aerobic-lock-236714/zones/us-west1-a/machineTypes/n1-stand

    network-interfaces
        network: $(external-query google::compute-network {name: "default"})
    end

    initialize-disks
        boot: true

        initialize-params
            disk-name: "jc-gyro-boot-disk"
            source-image: "projects/debian-cloud/global/images/family/debian-9"
        end
    end
end
```

Initially this works ok but subsequent changes (i.e. `gyro up` with changes) will fail. If the changes are only to the resource with the reference it works but if any other resource changes this will fail.

Like the previous example, debugging shows that in this case `isExternal` is false. This causes Gyro to attempt to generate an internal reference, such as `$(google::compute-network <name>)` but since this is an external reference there is no `<name>` (i.e. the value in a `PairNode`). This is the NPE trigger.
