### ISSUE TITLE
Convert Enums to Strings for Easier Comparisons

### ISSUE THREAD

**Issue by tloisel1** [perfectsense/gyro#191]
**Is your feature request related to a problem? Please describe.**
There is an enum field on a Resource (`gyro.aws.acm.AcmCertificateResource#status`) that I would like to do use in a comparison. The status of the certificate will dictate whether it can be used on a CloudFront distribution or ALB. I would like to add logic in my configurations to automatically detect this scenario, so when the certificate is issued, it will be applied without changing Gyro configurations.

**Describe the solution you'd like**
I would like to be able to create this if statement:
```
@if $(acm-certificate).status = 'ISSUED'
   // configure on CF distribution
-else
  // other configuration
@end
```

**Describe alternatives you've considered**
The alternative would be to call the `#toString()` method on the object. While this is available, it is not clear that this can be used and that naming conversions are necessary `to-string`

**Additional context**

**Comment by beetlebugorg** [comment]
From @hyoolim on Gitter:

This is the code that handles equals: https://github.com/perfectsense/gyro/blob/master/core/src/main/java/gyro/core/scope/NodeEvaluator.java#L101

The suggested change to handle enums better is:

```java
(l, r) -> {
    if (l != null && r != null) {
        Class<?> lClass = l.getClass();
        Class<?> rClass = r.getClass();

        if (!lClass.equals(rClass)) {
            Object rConverted = ObjectUtils.to(lClass, r);

            if (rConverted != null) {
                return Objects.equals(l, rConverted);

            } else {
                Object lConverted = ObjectUtils.to(rClass, l);

                if (lConverted != null) {
                    return Objects.equals(lConverted, r);
                }
            }
        }
    }

    return Objects.equals(l, r);
}
```

**Comment by tloisel1** [comment]
Closed with https://github.com/perfectsense/gyro/pull/192
