### ISSUE TITLE
Wait directives are not executed in Workflow Updates

### ISSUE THREAD

**Issue by tloisel1** [perfectsense/gyro#206]
**Describe the bug**
I have a stage in a workflow that has an `UpdateAction` with a `@wait` directive. When this is executed, the `wait` is never executed.

**To Reproduce**
I have a stage where the load balancers associated with an autoscale group is modified. In order to ensure no downtime, I'd like the wait to ensure all instances are healthy before further action is taken:
```
    stage foo
        @workflow::update $(aws::autoscaling-group frontend-verify)
            classic-load-balancers: [
                $(aws::load-balancer frontend),
                $(aws::load-balancer cms)
            ]

            @wait: $(aws::load-balancer frontend).instance-health.InService = $(aws::load-balancer frontend).instance-health.Total -check-every 60 -at-most 600
        @end
   end
```
This wait is never executed.

**Additional context**
This seems to be okay for `@workflow::create` directives.

On additional digging, it seems like the `Scope` that the `WaitDirectiveProcessor` isn't included when the ChangeProcessors are resolved for that Update.

**Comment by beetlebugorg** [comment]
Turns out this is actually a much deeper issue with how `LoadBalancerResource` is modeled. The short version is that `$(aws::load-balancer frontend).instances` in your workflow (not shown above) always returns null because the instances are added by the autoscale group rather than the Gyro configuration.
