### ISSUE TITLE
Exceptions while saving state causes empty state file to be saved

### ISSUE THREAD

**Issue by beetlebugorg** [perfectsense/gyro#207]
If an exception occurs [here](https://github.com/perfectsense/gyro/blob/master/core/src/main/java/gyro/core/scope/State.java#L201-L212) in `State.save()` the resulting state file will be empty.

The issue is because `LocalFileBackend` always opens a temporary file and then automatically moves into requested location upon calling `close()` on the file output stream.

Atomic move in `LocalFileBackend`: https://github.com/perfectsense/gyro/blob/master/core/src/main/java/gyro/core/LocalFileBackend.java#L71

**Comment by kluman** [comment]
Code looks good. 

I tested a `gyro up` that throws an error during the State save before and after the code change and now when error occurs the state file is no longer emptied out and the current state remains.
