### ISSUE TITLE
`@for` directives not setting variable if it has been used set earlier in config

### ISSUE THREAD

**Issue by ErikBZ** [perfectsense/gyro#210]
**Describe the bug**
If a variable is reused inside a @for directive, after it's been set to some value, then it will not be set to the values in the array that was passed in.

**To Reproduce**
You can run the following gyro config to reproduce the issue
```
some_var: "item"

a_list: ["hi", "hello", "how", "are"]
@for some_var -in $(a_list)
    # The excepted output is "hi" "hello" "how" "are"
    # but we get "item1" instead.
    @print: $(some_var)
@end
```

**Expected behavior**
The variable that was reused to capture items in a collection should be set to each of those items, or gyro should print an error if variable shadowing is not allowed.

**Additional context**
The following will also fail, even though the variable "some_var" should be out of scope by the time it gets to the second for loop.
```
@for thing -in ["item"]
    some_var: $(thing)
    @print: "Here is the first value: $(some_var)"
@end

a_list: ["hi", "hello", "how", "are"]
@for some_var -in $(a_list)
    @print: "A value from the array: $(some_var)"
@end
```

**Comment by beetlebugorg** [comment]
We need to be more clear on scoping rules in Gyro and enforce them to avoid issues like this. Here are the rules as I see them now:

There are two scopes, `global`, and `file`. 

- Global scope is any variable defined in `.gyro/init.gyro`. Variables defined as global are available in any Gyro configuration within the project.
- File scope is any variable defined within a particular file. Variables defined in a file are only available within that file. 

**Variables are immutable.**

The examples in the original issue comment would error with these scoping rules in place.
