### ISSUE TITLE
State Backend: Cloud Storage

### ISSUE THREAD

**Issue by beetlebugorg** [perfectsense/gyro#236]
Implement a new state backend that stores state in a cloud providers file storage such as S3.

Questions to think about:

- How does the S3 bucket get created initially?
- How does locking work to avoid two people from running gyro at the same time?
- Is only `gyro up` locked?

Requirements:

- Method to configure which file backend to use for saving state. This should be configured in `.gyro/init.gyro`.
- Method to migration between file backends.
- Method to implement locking so only one `gyro up` can happen at a time.

**Comment by alex-lambrides** [comment]
Locking should work independent of state backend, so the locking functionality has been separated into another ticket: #269
