### ISSUE TITLE
Quote Escaping in Gyro Strings

### ISSUE THREAD

**Issue by ErikBZ** [perfectsense/gyro#296]
The Google Service Account Role has a field "condition". The syntax for the conditions require double quotes, like
```
expression: 'resource.name.startsWith("projects/_/buckets/some_bucket/path") || 
resource.name.startsWith("projects/_/buckets/another_bucket/path")'
```

Resolvers don't work inside single quotes so there's no way to use variables to replace pieces of expression.

**Describe the solution you'd like**
I'd like to be able to escape double quotes inside of gyro strings. This will allow us to use the required syntax for Google conditions and use gyro variables to build the expressions, 

**Additional context**
Here's how gyro currently works:
```
var: "Test"
var2: "The cat says: \"$(var)\""

@print: $(var2)
```
will print out 
```"The cat says: \"Test\""```
I would expect this to be
```"The cast says: "Test""```

**Comment by deepanjan90** [comment]
After investigating, we found that the output `"The cat says: \"Test\""` is the correct one as the `@print` directive converts the string to `json` syntax which is responsible for escaping of the `"` to `\"` and as such gyro is able to parse `\"` escaped double quotes correctly.

Related to the original issue with setting the conditions having escaped quotes `\"` also worked when tried.
