### ISSUE TITLE
Optimization 4 - BeanInfo

### ISSUE THREAD

**Issue by beetlebugorg** [perfectsense/gyro#314]
### Optimization 4 - BeanInfo

Gyro introspects all Resource/Diffable classes and builds up a type object, `DiffableType`. This can be slow because Java looks for a few custom classes that are not implemented which can be expensive.

This prototype implements BeanInfo on `Diffable`.

https://github.com/perfectsense/gyro/blob/feature/performance/core/src/main/java/gyro/core/resource/Diffable.java#L172-L212

_Start Impact: ~750ms_

**Comment by sshyub** [comment]
PR: https://github.com/perfectsense/gyro/pull/318
