### ISSUE TITLE
Optimization 6 - Add copy(String source, String dest) to FileBackend

### ISSUE THREAD

**Issue by beetlebugorg** [perfectsense/gyro#316]
Some custom resource implementations use FileBackend to copy a file from one place to another within a FileBackend. For example, copying a build artifact to a location production infrastructure can be sure it'll always exists.

Method signature: `FileBackend.copy(String source, String destination)`

The default implementation should use `IoUtils.copy(inputStream, out)`.

_Originally posted by @deepanjan90 in https://github.com/perfectsense/gyro/pull/317#issuecomment-669446374_

It would be nice to have the ability to specify the ACCESS Type when uploading or Copying files using a filebackend.
The specific filebackend implementation should deal with the how to / if at all enforce them

The method signature in question are `copy()` and `openOutput()` of `FileBackend.java`

The signature change will also have to be propagated to all the classes across providers that implement the `FileBackend.java` class

**Comment by sshyub** [comment]
PR: https://github.com/perfectsense/gyro/pull/317
